import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title:{
    absolute :"",
    default :"nextjs-document",
    template :"%s | code Evalution",
  },
  description :"Generated by next-js"
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <p className="bg-green-500 p-3 text-center">header</p> */}
      <body className={inter.className}>{children}</body>
      {/* <footer>Footer</footer> */}
    </html>
  );
}
